### ISSUE TITLE
Email regex too strict

### ISSUE THREAD

**Issue by d-Pixie** [my-codeworks/fortnox-api#130]
We got a validation error from Bolagskraft on a valid email: kanal_75_ab-faktura@mail.unit4agresso.readsoftonline.com (https://app.bugsnag.com/your-codeworks/bolagskraft/errors/5a849e0b7482aa00182c686c for those with access).

We should look over the regex and find one that is more permissible in its matching.

**Comment by ehannes** [comment]
As you can see above, this is already resolved :)
