### ISSUE TITLE
Fix mapping from JSON to Ruby objects for Attributes

### ISSUE THREAD

**Issue by ehannes** [my-codeworks/fortnox-api#15]
Some model attributes needs special care when converting to/from JSON. This is currently handled in the model's repository. This functionality is needed for our `Valid Objects`/`Attributes` (placed in `lib/fortnox/api/models/attributes`) too.

**Comment by d-Pixie** [comment]
So ... I know you described this to me before, but I can't remember :) The attributes are just mixed into the model, so any initialization from the repository for a new model instance, or serialization of it out, should be covered by the current code.

Could you give an example of what is not working with expected and current result please?

**Comment by ehannes** [comment]
Actually, I am not sure this is not working as intended. I just assumed that it would work differently for `Attributes`, but that may not be the case!

**Comment by d-Pixie** [comment]
Will this also be solved by https://github.com/my-codeworks/fortnox-api/pull/23 ?

**Comment by ehannes** [comment]
That depends on what testing I manage to add in #23. If I don't include it there, I'll open a new PR just for this issue.

**Comment by ehannes** [comment]
This was not solved in #23. But maybe it's working right "out of the box". I'll need to test this.
