### ISSUE TITLE
Save records with other id than 1

### ISSUE THREAD

**Issue by ehannes** [my-codeworks/fortnox-api#39]
When trying to save a record and there are existing ones in Fortnox, I get the following error:
```
  2) Fortnox::API::Repository::Customer.save old (update existing) include updated "Name"
     Failure/Error: raise Fortnox::API::RemoteServerError, message
     
     Fortnox::API::RemoteServerError:
       Kundnummer 1 används redan.
```

It looks like the id is fixed on 1.

**Comment by ehannes** [comment]
This is the json being send:

```
{"Customer":{"Currency":"SEK","CustomerNumber":"1","Email":"","EmailInvoice":"","EmailInvoiceBCC":"","EmailInvoiceCC":"","EmailOffer":"","EmailOfferBCC":"","EmailOfferCC":"","EmailOrder":"","EmailOrderBCC":"
","EmailOrderCC":"","InvoiceRemark":"","Name":"Updated customer","OrganisationNumber":"","OurReference":"","PriceList":"A","Project":"","ShowPriceVATIncluded":false,"TermsOfDelivery":"","TermsOfPayment":"","
Type":"COMPANY","VATNumber":"","VATType":"SEVAT","WayOfDelivery":"","YourReference":""}}
```

It says `"CustomerNumber":"1"`...

**Comment by d-Pixie** [comment]
You need to filter out the `CustomerNumber` property (or more generally the `unique_id` property) when saving an existing record. That logic should go into the repo savers module logic and rely on the property name given as `unique_id` in the repo options.

**Comment by ehannes** [comment]
Why is `CustomerNumber` set to 1 at the first place?

**Comment by ehannes** [comment]
This was false alarm! The request was incorrect.
