### ISSUE TITLE
Refactor the JSON helper module to be standalone

### ISSUE THREAD

**Issue by d-Pixie** [my-codeworks/fortnox-api#52]
Remove the implicit dependence on the @options object and make it explicit by sending all of the required parts that are now taken out of the @options object in as parameters.

**Comment by d-Pixie** [comment]
See also https://github.com/my-codeworks/fortnox-api/pull/48#issuecomment-198304272 for discussion on this and remember to fix the relevant tests after the refactor.

**Comment by d-Pixie** [comment]
Done and done ...

**Comment by ehannes** [comment]
Next time, if you want, you can add `fixes #52` in the PR and that issue will be closed automatically when the PR is merged :)

**Comment by d-Pixie** [comment]
Ah, nice one!
